version: "2.3"

services:
  cvat:
    environment:
      CVAT_SHARE_URL: "Mounted from /s3"
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /home/ubuntu/mys3bucket
      o: bind