version: "2.3"

services:
  cvat:
    environment:
      ALLOWED_HOSTS: .amazonaws.com
      CVAT_SHARE_URL: "Mounted from /s3"
    ports:
      - "80:8080"
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /home/ubuntu/mys3bucket
      o: bind