#
# Copyright (C) 2018-2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
version: "2.3"

services:
  cvat:
    container_name: cvat
    image: cvat/server
    restart: always
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy: nuclio,${no_proxy}
        socks_proxy:
        USER: "django"
        DJANGO_CONFIGURATION: "production"
        TZ: "Etc/UTC"
        CLAM_AV: "no"
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ""
      ALLOWED_HOSTS: "*"
      CVAT_REDIS_HOST: "exp-redis-cvat-001.hscu4n.0001.usw2.cache.amazonaws.com"
      CVAT_POSTGRES_HOST: "database-cvat.cvcxedjal8qt.us-west-2.rds.amazonaws.com"
      #ALLOWED_HOSTS: .amazonaws.com
      CVAT_SHARE_URL: "Mounted from /s3"
    ports:
      - "80:8080"
    volumes:
      - cvat_share:/home/django/share:ro
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - cvat_models:/home/django/models

  cvat_proxy:
    container_name: cvat_proxy
    image: nginx:stable-alpine
    restart: always
    depends_on:
      - cvat
    environment:
      CVAT_HOST: localhost
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/obsidian-1307.supahands.com/fullchain.pem
      - /etc/letsencrypt/live/obsidian-1307.supahands.com/privkey.pem
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./cvat_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cvat_proxy/conf.d/cvat.conf.template:/etc/nginx/conf.d/cvat.conf.template:ro
    command: /bin/sh -c "envsubst '$$CVAT_HOST' < /etc/nginx/conf.d/cvat.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  serverless:
    container_name: nuclio
    image: quay.io/nuclio/dashboard:1.4.8-amd64
    restart: always
    networks:
      default:
        aliases:
          - nuclio
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      http_proxy:
      https_proxy:
      no_proxy: 172.28.0.1,${no_proxy}
      NUCLIO_CHECK_FUNCTION_CONTAINERS_HEALTHINESS: "true"
    ports:
      - "8070:8070"

networks:
  default:
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

volumes:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_models:
  cvat_share:
    driver_opts:
      type: none
      device: /home/ubuntu/mys3bucket
      o: bind
